export interface FontRecord {
  id: string;
  familyName: string;
  provider: "google" | "local" | "custom";
  classification: "serif" | "sans" | "script" | "decorative";
  subclassification: string;
  description: string;
  supportedWeights: number[];
  weddingTags: string[];
  bestFor: string[];
  googleFontUrl?: string; // Direct Google Fonts CSS URL — used by font-resolver for canvas injection
  licensing: {
    licenseName: string;
    commercialApproved: boolean;
    embeddingApproved: boolean;
    exportApproved: boolean;
  };
  sampleSvgPath?: string;
}

const OFL = {
  licenseName: "OFL (Open Font License)",
  commercialApproved: true,
  embeddingApproved: true,
  exportApproved: true,
};

export const CURATED_FONTS: FontRecord[] = [
  // ─── HIGH-CONTRAST SERIFS ─────────────────────────────────────────────────
  {
    id: "cormorant_garamond",
    familyName: "Cormorant Garamond",
    provider: "google",
    classification: "serif",
    subclassification: "high_contrast_serif",
    description: "Refined capitals, elegant high contrast, and strong editorial luxury character.",
    supportedWeights: [300, 400, 500, 600, 700],
    weddingTags: ["editorial", "luxury", "formal", "high contrast", "romantic", "best for initials"],
    bestFor: ["couple wordmarks", "formal invitations", "editorial monograms"],
    googleFontUrl: "https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,300..700;1,300..700&display=swap",
    licensing: OFL,
  },
  {
    id: "cormorant",
    familyName: "Cormorant",
    provider: "google",
    classification: "serif",
    subclassification: "high_contrast_serif",
    description: "The broader Cormorant family — ultra-refined display serif with swash variants.",
    supportedWeights: [300, 400, 500, 600, 700],
    weddingTags: ["editorial", "luxury", "swash", "display"],
    bestFor: ["display headlines", "swash initials", "luxury wordmarks"],
    googleFontUrl: "https://fonts.googleapis.com/css2?family=Cormorant:ital,wght@0,300..700;1,300..700&display=swap",
    licensing: OFL,
  },
  {
    id: "bodoni",
    familyName: "Bodoni",
    provider: "google",
    classification: "serif",
    subclassification: "didone_serif",
    description: "Stately Didone serif with extreme vertical stress and dramatic thick-thin strokes.",
    supportedWeights: [400, 600, 800, 900],
    weddingTags: ["black tie", "high fashion", "french editorial", "dramatic"],
    bestFor: ["parisian wordmarks", "black tie monograms", "high fashion logos"],
    googleFontUrl: "https://fonts.googleapis.com/css2?family=Bodoni+Moda:ital,opsz,wght@0,6..96,400..900;1,6..96,400..900&display=swap",
    licensing: OFL,
  },
  {
    id: "cinzel",
    familyName: "Cinzel",
    provider: "google",
    classification: "serif",
    subclassification: "classical_roman_serif",
    description: "Inspired by 1st-century Roman inscriptions, classical proportions with refined serifs.",
    supportedWeights: [400, 600, 700, 900],
    weddingTags: ["heritage", "european estate", "classical", "formal", "all caps"],
    bestFor: ["crest monograms", "estate logos", "formal dates"],
    googleFontUrl: "https://fonts.googleapis.com/css2?family=Cinzel:wght@400..900&display=swap",
    licensing: OFL,
  },
  {
    id: "cinzel_decorative",
    familyName: "Cinzel Decorative",
    provider: "google",
    classification: "decorative",
    subclassification: "classical_roman_decorative",
    description: "Ornate decorative version of Cinzel — classical Roman forms with decorative flourishes.",
    supportedWeights: [400, 700, 900],
    weddingTags: ["ornate", "heritage", "decorative", "classical", "formal", "all caps"],
    bestFor: ["crest logos", "luxury covers", "ornate headlines"],
    googleFontUrl: "https://fonts.googleapis.com/css2?family=Cinzel+Decorative:wght@400;700;900&display=swap",
    licensing: OFL,
  },
  {
    id: "playfair_display",
    familyName: "Playfair Display",
    provider: "google",
    classification: "serif",
    subclassification: "high_contrast_serif",
    description: "Transitional display serif with graceful letterforms and beautiful ampersands.",
    supportedWeights: [400, 600, 700, 800, 900],
    weddingTags: ["romantic", "traditional", "elegant", "high contrast"],
    bestFor: ["stacked wordmarks", "couples names", "save the dates"],
    googleFontUrl: "https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400..900;1,400..900&display=swap",
    licensing: OFL,
  },
  {
    id: "eb_garamond",
    familyName: "EB Garamond",
    provider: "google",
    classification: "serif",
    subclassification: "old_style_serif",
    description: "Revival of the classic Claude Garamond typeface — timeless old-style elegance.",
    supportedWeights: [400, 500, 600, 700, 800],
    weddingTags: ["classic", "timeless", "old style", "literary"],
    bestFor: ["literary wedding identity", "vintage formal", "classic monograms"],
    googleFontUrl: "https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,400..800;1,400..800&display=swap",
    licensing: OFL,
  },
  {
    id: "dm_serif_display",
    familyName: "DM Serif Display",
    provider: "google",
    classification: "serif",
    subclassification: "display_serif",
    description: "Crisp transitional display serif with strong personality and refined details.",
    supportedWeights: [400],
    weddingTags: ["contemporary", "editorial", "clean", "display"],
    bestFor: ["editorial wedding marks", "display headlines", "clean monograms"],
    googleFontUrl: "https://fonts.googleapis.com/css2?family=DM+Serif+Display:ital@0;1&display=swap",
    licensing: OFL,
  },
  {
    id: "libre_baskerville",
    familyName: "Libre Baskerville",
    provider: "google",
    classification: "serif",
    subclassification: "transitional_serif",
    description: "Generous x-height Baskerville revival — strong, readable, and classically elegant.",
    supportedWeights: [400, 700],
    weddingTags: ["classic", "baskerville", "traditional", "clean serif"],
    bestFor: ["body text", "traditional marks", "balanced wordmarks"],
    googleFontUrl: "https://fonts.googleapis.com/css2?family=Libre+Baskerville:ital,wght@0,400;0,700;1,400&display=swap",
    licensing: OFL,
  },
  {
    id: "lora",
    familyName: "Lora",
    provider: "google",
    classification: "serif",
    subclassification: "calligraphic_serif",
    description: "Well-balanced contemporary serif with roots in calligraphy — warm and literary.",
    supportedWeights: [400, 500, 600, 700],
    weddingTags: ["warm", "literary", "calligraphic", "contemporary"],
    bestFor: ["wedding body copy", "supporting wordmarks", "invitation text"],
    googleFontUrl: "https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,400..700;1,400..700&display=swap",
    licensing: OFL,
  },
  {
    id: "forum",
    familyName: "Forum",
    provider: "google",
    classification: "serif",
    subclassification: "classical_roman_serif",
    description: "Influenced by Roman stone-carving. All-caps classical serif with strong presence.",
    supportedWeights: [400],
    weddingTags: ["classical", "roman", "all caps", "heritage", "formal"],
    bestFor: ["crest monograms", "formal names", "all-caps wordmarks"],
    googleFontUrl: "https://fonts.googleapis.com/css2?family=Forum&display=swap",
    licensing: OFL,
  },
  {
    id: "italiana",
    familyName: "Italiana",
    provider: "google",
    classification: "serif",
    subclassification: "didone_serif",
    description: "Elegant Italian-inspired Didone with extreme contrast and refined hairline strokes.",
    supportedWeights: [400],
    weddingTags: ["italian", "luxury", "haute couture", "dramatic"],
    bestFor: ["haute couture marks", "luxury wordmarks", "italian estate identity"],
    googleFontUrl: "https://fonts.googleapis.com/css2?family=Italiana&display=swap",
    licensing: OFL,
  },
  {
    id: "marcellus",
    familyName: "Marcellus",
    provider: "google",
    classification: "serif",
    subclassification: "classical_roman_serif",
    description: "Roman-inspired serif with upright stress — clean, formal, and timeless.",
    supportedWeights: [400],
    weddingTags: ["roman", "classical", "formal", "clean"],
    bestFor: ["formal monograms", "estate names", "timeless wordmarks"],
    googleFontUrl: "https://fonts.googleapis.com/css2?family=Marcellus&display=swap",
    licensing: OFL,
  },
  {
    id: "orpheus_pro",
    familyName: "Orpheus Pro",
    provider: "google",
    classification: "serif",
    subclassification: "humanist_serif",
    description: "Humanist serif with optical balance and graceful proportions for wedding typography.",
    supportedWeights: [400],
    weddingTags: ["humanist", "balanced", "graceful", "editorial"],
    bestFor: ["balanced wordmarks", "elegant couples identity", "refined wedding marks"],
    googleFontUrl: "https://fonts.googleapis.com/css2?family=Orpheus+Pro&display=swap",
    licensing: OFL,
  },

  // ─── SANS-SERIF ────────────────────────────────────────────────────────────
  {
    id: "inter",
    familyName: "Inter",
    provider: "google",
    classification: "sans",
    subclassification: "minimal_sans",
    description: "Precision-engineered geometric sans-serif for clean modern minimalist wedding identity.",
    supportedWeights: [300, 400, 500, 600, 700],
    weddingTags: ["modern minimal", "clean", "architectural", "contemporary"],
    bestFor: ["minimal wordmarks", "supporting text", "dates and locations"],
    googleFontUrl: "https://fonts.googleapis.com/css2?family=Inter:wght@300..800&display=swap",
    licensing: OFL,
  },
  {
    id: "montserrat",
    familyName: "Montserrat",
    provider: "google",
    classification: "sans",
    subclassification: "geometric_sans",
    description: "Geometric sans-serif with clean lines — contemporary and versatile.",
    supportedWeights: [300, 400, 500, 600, 700, 800, 900],
    weddingTags: ["modern", "geometric", "clean", "versatile", "contemporary"],
    bestFor: ["modern wedding marks", "clean wordmarks", "hashtag text"],
    googleFontUrl: "https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,300..900;1,300..900&display=swap",
    licensing: OFL,
  },
  {
    id: "raleway",
    familyName: "Raleway",
    provider: "google",
    classification: "sans",
    subclassification: "elegant_sans",
    description: "Elegant sans-serif with unique W letterform — refined and fashionable.",
    supportedWeights: [100, 200, 300, 400, 500, 600, 700, 800, 900],
    weddingTags: ["elegant", "thin", "modern", "fashion"],
    bestFor: ["fashion-forward marks", "thin weight headlines", "elegant subtext"],
    googleFontUrl: "https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,100..900;1,100..900&display=swap",
    licensing: OFL,
  },
  {
    id: "josefin_sans",
    familyName: "Josefin Sans",
    provider: "google",
    classification: "sans",
    subclassification: "geometric_sans",
    description: "Inspired by 1920s geometric typefaces — clean, minimal, and highly distinctive.",
    supportedWeights: [100, 200, 300, 400, 600, 700],
    weddingTags: ["art deco", "1920s", "geometric", "minimal"],
    bestFor: ["art deco wedding marks", "geometric monograms", "minimal all-caps"],
    googleFontUrl: "https://fonts.googleapis.com/css2?family=Josefin+Sans:ital,wght@0,100..700;1,100..700&display=swap",
    licensing: OFL,
  },

  // ─── SCRIPT / CALLIGRAPHY ──────────────────────────────────────────────────
  {
    id: "alex_brush",
    familyName: "Alex Brush",
    provider: "google",
    classification: "script",
    subclassification: "formal_calligraphy",
    description: "Flowing formal calligraphy script with beautiful connecting swashes.",
    supportedWeights: [400],
    weddingTags: ["romantic", "calligraphy", "script accent"],
    bestFor: ["script name accents", "romantic initials"],
    googleFontUrl: "https://fonts.googleapis.com/css2?family=Alex+Brush&display=swap",
    licensing: OFL,
  },
  {
    id: "great_vibes",
    familyName: "Great Vibes",
    provider: "google",
    classification: "script",
    subclassification: "formal_calligraphy",
    description: "Beautifully connected formal script with graceful loops and swashes.",
    supportedWeights: [400],
    weddingTags: ["romantic", "calligraphy", "flowing", "formal script"],
    bestFor: ["couples names", "romantic monograms", "script wordmarks"],
    googleFontUrl: "https://fonts.googleapis.com/css2?family=Great+Vibes&display=swap",
    licensing: OFL,
  },
  {
    id: "allura",
    familyName: "Allura",
    provider: "google",
    classification: "script",
    subclassification: "formal_calligraphy",
    description: "Elegant formal script with a flowing, lush letterform character.",
    supportedWeights: [400],
    weddingTags: ["elegant", "flowing", "formal script", "romantic"],
    bestFor: ["romantic monograms", "formal script wordmarks"],
    googleFontUrl: "https://fonts.googleapis.com/css2?family=Allura&display=swap",
    licensing: OFL,
  },
  {
    id: "sacramento",
    familyName: "Sacramento",
    provider: "google",
    classification: "script",
    subclassification: "casual_script",
    description: "Casual connected script with a warm and approachable feel.",
    supportedWeights: [400],
    weddingTags: ["casual", "warm", "script", "handwritten"],
    bestFor: ["casual wedding marks", "modern calligraphy", "warm scripts"],
    googleFontUrl: "https://fonts.googleapis.com/css2?family=Sacramento&display=swap",
    licensing: OFL,
  },
  {
    id: "pinyon_script",
    familyName: "Pinyon Script",
    provider: "google",
    classification: "script",
    subclassification: "formal_calligraphy",
    description: "Highly formal copperplate-influenced script — graceful, classical, and ornate.",
    supportedWeights: [400],
    weddingTags: ["copperplate", "formal", "ornate", "classical script"],
    bestFor: ["formal invitations", "copperplate-style monograms", "black tie wedding identity"],
    googleFontUrl: "https://fonts.googleapis.com/css2?family=Pinyon+Script&display=swap",
    licensing: OFL,
  },
  {
    id: "tangerine",
    familyName: "Tangerine",
    provider: "google",
    classification: "script",
    subclassification: "formal_calligraphy",
    description: "Narrow formal script with expressive calligraphic strokes and italic flourishes.",
    supportedWeights: [400, 700],
    weddingTags: ["italic", "narrow", "calligraphic", "formal"],
    bestFor: ["names in script", "italic wedding marks", "narrow calligraphy"],
    googleFontUrl: "https://fonts.googleapis.com/css2?family=Tangerine:wght@400;700&display=swap",
    licensing: OFL,
  },
  {
    id: "mrs_saint_delafield",
    familyName: "Mrs Saint Delafield",
    provider: "google",
    classification: "script",
    subclassification: "formal_calligraphy",
    description: "Ultra-elegant formal script with extreme finesse and luxurious character.",
    supportedWeights: [400],
    weddingTags: ["ultra luxury", "formal", "elegant script", "fine"],
    bestFor: ["ultra-luxury wedding marks", "fine formal identity", "couture monograms"],
    googleFontUrl: "https://fonts.googleapis.com/css2?family=Mrs+Saint+Delafield&display=swap",
    licensing: OFL,
  },
  {
    id: "dancing_script",
    familyName: "Dancing Script",
    provider: "google",
    classification: "script",
    subclassification: "casual_script",
    description: "Lively casual script with a natural handwritten bounce and open forms.",
    supportedWeights: [400, 500, 600, 700],
    weddingTags: ["casual", "handwritten", "lively", "informal"],
    bestFor: ["casual wedding identity", "modern handwritten marks", "informal subtext"],
    googleFontUrl: "https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400..700&display=swap",
    licensing: OFL,
  },
];
