import { z } from "zod";

export const ReferenceInstructionSchema = z.object({
  imageUrl: z.string(),
  classification: z.enum([
    "typography",
    "layout",
    "floral",
    "ornament",
    "color",
    "style",
    "existing",
  ]),
  notes: z.string().optional(),
  strength: z.enum(["loose", "moderate", "strong"]).default("moderate"),
});

export const DesignBriefSchema = z.object({
  assetType: z.enum([
    "couple_logo",
    "couple_wordmark",
    "two_initial_monogram",
    "three_letter_monogram",
    "interlocking_monogram",
    "stacked_monogram",
    "mirrored_monogram",
    "wedding_crest",
    "botanical_wreath",
    "floral_cluster",
    "invitation_border",
    "invitation_divider",
    "corner_ornament",
    "save_the_date_mark",
    "welcome_sign_logo",
    "dance_floor_monogram",
    "photobooth_overlay_mark",
    "decorative_invitation_element",
  ]),
  primaryText: z.string(),
  secondaryText: z.string().optional().default(""),
  initials: z.array(z.string()).default([]),
  surname: z.string().optional().default(""),
  date: z.string().optional().default(""),
  location: z.string().optional().default(""),
  layout: z.enum([
    "horizontal",
    "stacked",
    "interlocking",
    "overlapping",
    "crest",
    "wreath",
    "corner",
    "border",
    "freeform",
  ]).default("stacked"),
  typographyCategory: z.enum([
    "high_contrast_serif",
    "old_style_serif",
    "classical_roman_serif",
    "didone_serif",
    "engraved_serif",
    "modern_minimal_sans",
    "editorial_sans",
    "copperplate_script",
    "formal_calligraphy",
    "monogram_display",
  ]).default("high_contrast_serif"),
  weddingStyle: z.string().default("editorial_luxury"),
  styleKeywords: z.array(z.string()).default(["elegant", "editorial", "minimal", "formal"]),
  colorMode: z.enum(["black_on_white", "white_on_black", "champagne_on_paper", "custom"]).default("black_on_white"),
  background: z.enum(["pure_white", "transparent", "warm_ivory", "black"]).default("pure_white"),
  ornamentType: z.string().default("none"),
  floralType: z.string().default("none"),
  referenceInstructions: z.array(ReferenceInstructionSchema).default([]),
  generationPrompt: z.string().default(""),
  negativePrompt: z.array(z.string()).default([
    "script font",
    "calligraphy",
    "mockup",
    "paper texture",
    "gray background",
    "flowers",
    "border",
    "extra text",
  ]),
  outputMode: z.enum(["ai", "vector", "hybrid"]).default("hybrid"),
  aspectRatio: z.enum(["1:1", "4:3", "3:4", "16:9"]).default("1:1"),
  canvasFormat: z.string().optional(),
  generationType: z.string().optional(),
  guidanceConfig: z.any().optional(),
  hasActiveBackground: z.boolean().optional().default(false),
  recommendedFonts: z.array(z.string()).default([]),
  productionNotes: z.array(z.string()).default([]),
});

export type ReferenceInstruction = z.infer<typeof ReferenceInstructionSchema>;
export type DesignBrief = z.infer<typeof DesignBriefSchema>;
