export interface SwatchColor {
  name: string;
  hex: string;
  role: "primary" | "accent" | "background" | "neutral" | "subtle";
}

export interface WeddingPaletteRecord {
  id: string;
  name: string;
  category: "traditional" | "floral" | "coastal" | "editorial" | "autumn";
  categoryLabel: string;
  description: string;
  weddingTags: string[];
  swatches: SwatchColor[];
}

export const CURATED_PALETTES: WeddingPaletteRecord[] = [
  // ── 1. FLORAL & BOTANICAL ──────────────────────────────────────────────────
  {
    id: "garden_rose_eucalyptus",
    name: "Garden Rose & Eucalyptus",
    category: "floral",
    categoryLabel: "Floral & Botanical",
    description: "Soft romantic blush rose petals grounded by muted botanical eucalyptus green.",
    weddingTags: ["blush", "eucalyptus", "garden rose", "romantic", "botanical"],
    swatches: [
      { name: "Blush Petal", hex: "#D8A47F", role: "primary" },
      { name: "Eucalyptus Green", hex: "#8EA38C", role: "accent" },
      { name: "Soft Linen", hex: "#FAF7F2", role: "background" },
      { name: "Muted Crimson", hex: "#9B4B52", role: "neutral" },
      { name: "Dusty Rose", hex: "#E9C3B4", role: "subtle" },
    ],
  },
  {
    id: "english_garden_hydrangea",
    name: "English Garden Hydrangea",
    category: "floral",
    categoryLabel: "Floral & Botanical",
    description: "Serene English estate garden tones featuring dusty periwinkle hydrangea, lavender lilac, and sage.",
    weddingTags: ["hydrangea", "english garden", "periwinkle", "estate floral", "lilac"],
    swatches: [
      { name: "Dusty Hydrangea Blue", hex: "#5C768D", role: "primary" },
      { name: "Soft Lilac Bloom", hex: "#B8A3C4", role: "accent" },
      { name: "English Ivory", hex: "#FAF9F6", role: "background" },
      { name: "Pale Sage Leaf", hex: "#94A38B", role: "neutral" },
      { name: "Deep Slate Foliage", hex: "#3A4B58", role: "subtle" },
    ],
  },
  {
    id: "peony_burgundy",
    name: "Peony & Velvet Burgundy",
    category: "floral",
    categoryLabel: "Floral & Botanical",
    description: "Lush deep burgundy wine tones paired with soft peony pink and sage foliage.",
    weddingTags: ["burgundy", "peony", "dramatic floral", "fall floral", "lush"],
    swatches: [
      { name: "Velvet Burgundy", hex: "#581825", role: "primary" },
      { name: "Peony Pink", hex: "#F4D3C6", role: "accent" },
      { name: "Fresh Sage", hex: "#7E8D7B", role: "background" },
      { name: "Rosewood", hex: "#8B4255", role: "neutral" },
      { name: "Warm Pearl", hex: "#FAF8F6", role: "subtle" },
    ],
  },
  {
    id: "chateau_wisteria_blush",
    name: "Chateau Wisteria & Soft Blush",
    category: "floral",
    categoryLabel: "Floral & Botanical",
    description: "French chateau courtyard palette with cascading wisteria violet and ballet slipper blush.",
    weddingTags: ["wisteria", "chateau", "french floral", "blush", "violet"],
    swatches: [
      { name: "Wisteria Violet", hex: "#8C7496", role: "primary" },
      { name: "Ballet Blush", hex: "#F7E1D7", role: "accent" },
      { name: "Chateau Linen", hex: "#FAF6F0", role: "background" },
      { name: "Gilded Gold", hex: "#B89748", role: "neutral" },
      { name: "Deep Plum", hex: "#4A354A", role: "subtle" },
    ],
  },
  {
    id: "french_lavender_sage",
    name: "French Lavender & Sage",
    category: "floral",
    categoryLabel: "Floral & Botanical",
    description: "Provencal countryside palette with soft lavender dusk and muted dried sage.",
    weddingTags: ["lavender", "provence", "sage", "romantic", "french"],
    swatches: [
      { name: "Lavender Dusk", hex: "#7C75A3", role: "primary" },
      { name: "Dried Sage", hex: "#7D8D7E", role: "accent" },
      { name: "Provencal Cream", hex: "#FAF8F5", role: "background" },
      { name: "Plum Accent", hex: "#5B4059", role: "neutral" },
      { name: "Soft Mauve", hex: "#D2C9DB", role: "subtle" },
    ],
  },
  {
    id: "white_anemone_greenery",
    name: "White Anemone & Botanical Fern",
    category: "floral",
    categoryLabel: "Floral & Botanical",
    description: "Crisp white anemones with dark obsidian centers surrounded by deep botanical fern foliage.",
    weddingTags: ["anemone", "botanical green", "crisp white", "modern floral", "monochrome green"],
    swatches: [
      { name: "Deep Botanical Fern", hex: "#2D4A3E", role: "primary" },
      { name: "Crisp Anemone White", hex: "#FFFFFF", role: "background" },
      { name: "Obsidian Center", hex: "#111827", role: "accent" },
      { name: "Soft Moss", hex: "#84A98C", role: "neutral" },
      { name: "Parchment Linen", hex: "#F4F1EA", role: "subtle" },
    ],
  },
  {
    id: "ranunculus_peach_fizz",
    name: "Ranunculus & Peach Apricot",
    category: "floral",
    categoryLabel: "Floral & Botanical",
    description: "Warm glowing peach ranunculus blooms paired with soft apricot and olive leaves.",
    weddingTags: ["ranunculus", "peach", "apricot", "warm floral", "spring"],
    swatches: [
      { name: "Peach Apricot", hex: "#F4A261", role: "primary" },
      { name: "Terracotta Coral", hex: "#E76F51", role: "accent" },
      { name: "Vanilla Cream", hex: "#FFF8F0", role: "background" },
      { name: "Olive Leaf", hex: "#606C38", role: "neutral" },
      { name: "Gold Dust", hex: "#D4AF37", role: "subtle" },
    ],
  },
  {
    id: "wildflower_meadow",
    name: "Wildflower Meadow",
    category: "floral",
    categoryLabel: "Floral & Botanical",
    description: "Vibrant botanical palette inspired by sunlit summer wildflower fields.",
    weddingTags: ["wildflower", "summer", "botanical", "buttercup", "cornflower"],
    swatches: [
      { name: "Buttercup Gold", hex: "#D9A036", role: "primary" },
      { name: "Dusty Cornflower", hex: "#5B80A8", role: "accent" },
      { name: "Meadow Green", hex: "#738B67", role: "background" },
      { name: "Cream Paper", hex: "#FBF9F5", role: "neutral" },
      { name: "Soft Rust", hex: "#C87D55", role: "subtle" },
    ],
  },
  {
    id: "olive_grove_terracotta",
    name: "Olive Grove & Terracotta",
    category: "floral",
    categoryLabel: "Floral & Botanical",
    description: "Earthy Mediterranean olive foliage paired with sun-baked terracotta tile.",
    weddingTags: ["olive", "terracotta", "mediterranean", "earthy", "tuscan"],
    swatches: [
      { name: "Mediterranean Olive", hex: "#586048", role: "primary" },
      { name: "Tuscan Terracotta", hex: "#C87B64", role: "accent" },
      { name: "Warm Sand", hex: "#EADCC9", role: "background" },
      { name: "Espresso Bark", hex: "#3A2A23", role: "neutral" },
      { name: "Soft Almond", hex: "#F5EFE6", role: "subtle" },
    ],
  },

  // ── 2. COASTAL & DESTINATION ───────────────────────────────────────────────
  {
    id: "coastal_navy_seasalt",
    name: "Coastal Navy & Sea Salt",
    category: "coastal",
    categoryLabel: "Coastal & Destination",
    description: "Seaside estate palette with crisp ocean navy and sun-bleached linen.",
    weddingTags: ["coastal", "navy", "sea salt", "ocean", "nautical luxury"],
    swatches: [
      { name: "Deep Ocean Navy", hex: "#1E293B", role: "primary" },
      { name: "Brass Accent", hex: "#CA8A04", role: "accent" },
      { name: "Sea Salt Linen", hex: "#F8FAFC", role: "background" },
      { name: "Driftwood Slate", hex: "#64748B", role: "neutral" },
      { name: "Cloud Grey", hex: "#E2E8F0", role: "subtle" },
    ],
  },
  {
    id: "santorini_aegean_white",
    name: "Santorini Aegean & Chalk White",
    category: "coastal",
    categoryLabel: "Coastal & Destination",
    description: "Greek island aesthetic with deep Aegean blue, sun-baked terracotta, and whitewashed stone.",
    weddingTags: ["santorini", "aegean blue", "greece", "whitewashed", "mediterranean"],
    swatches: [
      { name: "Aegean Deep Blue", hex: "#005F73", role: "primary" },
      { name: "Chalk White", hex: "#FFFFFF", role: "background" },
      { name: "Sunwashed Ochre", hex: "#EE9B00", role: "accent" },
      { name: "Sea Foam Teal", hex: "#94D2BD", role: "neutral" },
      { name: "Deep Midnight Indigo", hex: "#0A2540", role: "subtle" },
    ],
  },
  {
    id: "lake_como_villa",
    name: "Lake Como Villa & Cypress",
    category: "coastal",
    categoryLabel: "Coastal & Destination",
    description: "Northern Italian lakefront luxury with deep teal water, villa terrazzo, and Italian cypress.",
    weddingTags: ["lake como", "italy", "villa luxury", "lakefront", "cypress"],
    swatches: [
      { name: "Lake Como Teal", hex: "#1B4965", role: "primary" },
      { name: "Italian Cypress", hex: "#2C5E3B", role: "accent" },
      { name: "Villa Terrazzo Linen", hex: "#F7F3E9", role: "background" },
      { name: "Aged Champagne", hex: "#E9D8A6", role: "neutral" },
      { name: "Deep Midnight", hex: "#0F2027", role: "subtle" },
    ],
  },
  {
    id: "amalfi_citrus_tile",
    name: "Amalfi Citrus & Majolica Tile",
    category: "coastal",
    categoryLabel: "Coastal & Destination",
    description: "Vibrant Italian coastline palette inspired by lemon groves and blue majolica tilework.",
    weddingTags: ["amalfi", "citrus", "italy", "tile", "destination"],
    swatches: [
      { name: "Majolica Blue", hex: "#1E40AF", role: "primary" },
      { name: "Limoncello Yellow", hex: "#EAB308", role: "accent" },
      { name: "Terracotta Brick", hex: "#C2410C", role: "neutral" },
      { name: "Italian Linen", hex: "#FAFAFA", role: "background" },
      { name: "Sea Foam Blue", hex: "#E0F2FE", role: "subtle" },
    ],
  },
  {
    id: "harbor_island_pink_sand",
    name: "Harbor Island Pink Sand & Sea Glass",
    category: "coastal",
    categoryLabel: "Coastal & Destination",
    description: "Bahamian seaside destination identity combining soft pink coral sands and sea glass mint.",
    weddingTags: ["pink sand", "bahamas", "sea glass", "caribbean", "coastal chic"],
    swatches: [
      { name: "Pink Sand Coral", hex: "#E8C5C8", role: "primary" },
      { name: "Sea Glass Mint", hex: "#A8DADC", role: "accent" },
      { name: "Deep Ocean Ink", hex: "#1D3557", role: "neutral" },
      { name: "Pure Shell White", hex: "#FAF9F6", role: "background" },
      { name: "Sunset Gold", hex: "#E9C46A", role: "subtle" },
    ],
  },
  {
    id: "big_sur_redwood_mist",
    name: "Big Sur Redwood & Pacific Mist",
    category: "coastal",
    categoryLabel: "Coastal & Destination",
    description: "Dramatic Northern California coast where ocean ocean mist meets ancient redwood forests.",
    weddingTags: ["big sur", "pacific", "redwood", "coastal forest", "california"],
    swatches: [
      { name: "Pacific Ocean Blue", hex: "#2B4C5E", role: "primary" },
      { name: "Redwood Bark", hex: "#5C3A21", role: "accent" },
      { name: "Pacific Mist", hex: "#D8E2DC", role: "background" },
      { name: "Sage Sea Foam", hex: "#94D2BD", role: "neutral" },
      { name: "Pearl White", hex: "#F9F9FB", role: "subtle" },
    ],
  },
  {
    id: "st_tropez_riviera",
    name: "St. Tropez Riviera & Peach Coral",
    category: "coastal",
    categoryLabel: "Coastal & Destination",
    description: "French Riviera beach club luxury with azure sea blue and warm peach sunlit coral.",
    weddingTags: ["st tropez", "french riviera", "azure blue", "peach", "beach luxury"],
    swatches: [
      { name: "Riviera Azure Blue", hex: "#0077B6", role: "primary" },
      { name: "Beach Peach Coral", hex: "#F4A261", role: "accent" },
      { name: "Linen White", hex: "#FAF9F6", role: "background" },
      { name: "Gilded Sun", hex: "#E9C46A", role: "neutral" },
      { name: "Deep Navy Blue", hex: "#03045E", role: "subtle" },
    ],
  },
  {
    id: "cabo_sunset_sandstone",
    name: "Cabo Sunset & Desert Sandstone",
    category: "coastal",
    categoryLabel: "Coastal & Destination",
    description: "Baja Mexico coastal desert palette featuring warm terracotta sandstone and Pacific teal.",
    weddingTags: ["cabo", "baja", "desert coastal", "terracotta", "mexico"],
    swatches: [
      { name: "Sandstone Ochre", hex: "#DDA15E", role: "primary" },
      { name: "Cabo Coral Sunset", hex: "#F4A261", role: "accent" },
      { name: "Pacific Ocean Teal", hex: "#2A9D8F", role: "neutral" },
      { name: "Desert Linen", hex: "#FAF6F0", role: "background" },
      { name: "Deep Bark", hex: "#BC6C25", role: "subtle" },
    ],
  },

  // ── 3. TRADITIONAL & BLACK TIE ─────────────────────────────────────────────
  {
    id: "parisian_black_tie",
    name: "Parisian Black Tie",
    category: "traditional",
    categoryLabel: "Traditional & Black Tie",
    description: "Classic high-contrast black tie stationery identity with burnished gold accents.",
    weddingTags: ["black tie", "formal", "parisian", "high contrast", "editorial"],
    swatches: [
      { name: "Onyx Black", hex: "#1C1917", role: "primary" },
      { name: "Vow Gold", hex: "#C9A251", role: "accent" },
      { name: "French Cream", hex: "#FBF9F5", role: "background" },
      { name: "Pewter Slate", hex: "#57534E", role: "neutral" },
      { name: "Pearl Grey", hex: "#E7E5E4", role: "subtle" },
    ],
  },
  {
    id: "estate_champagne",
    name: "Estate Champagne",
    category: "traditional",
    categoryLabel: "Traditional & Black Tie",
    description: "Refined European estate palette with warm champagne tones and deep espresso text.",
    weddingTags: ["champagne", "estate", "european", "heritage", "warm"],
    swatches: [
      { name: "Deep Espresso", hex: "#3A2E2B", role: "primary" },
      { name: "Burnished Brass", hex: "#D4AF37", role: "accent" },
      { name: "Warm Champagne", hex: "#E8D8C8", role: "background" },
      { name: "Estate Linen", hex: "#F5F2EB", role: "neutral" },
      { name: "Soft Bronze", hex: "#8C7A6B", role: "subtle" },
    ],
  },
  {
    id: "heritage_gold_ivory",
    name: "Heritage Gold & Ivory",
    category: "traditional",
    categoryLabel: "Traditional & Black Tie",
    description: "Time-tested luxury stationery palette featuring gold leaf accent tones.",
    weddingTags: ["gold leaf", "ivory", "classic", "formal", "crest"],
    swatches: [
      { name: "Classic Gold", hex: "#C9A251", role: "primary" },
      { name: "Midnight Ink", hex: "#0F172A", role: "accent" },
      { name: "Pure Ivory", hex: "#FAF8F5", role: "background" },
      { name: "Antique Brass", hex: "#A38338", role: "neutral" },
      { name: "Parchment", hex: "#F3EFE6", role: "subtle" },
    ],
  },
  {
    id: "cotswolds_limestone_sage",
    name: "Cotswolds Limestone & Sage",
    category: "traditional",
    categoryLabel: "Traditional & Black Tie",
    description: "Classic English countryside estate featuring honey-colored Cotswold stone and sage foliage.",
    weddingTags: ["cotswolds", "english estate", "limestone", "sage", "heritage"],
    swatches: [
      { name: "Limestone Cream", hex: "#EBE4D8", role: "background" },
      { name: "Cotswolds Sage", hex: "#7E8D7B", role: "accent" },
      { name: "Deep Charcoal Ink", hex: "#2C2C2C", role: "primary" },
      { name: "Heritage Gold", hex: "#C9A251", role: "neutral" },
      { name: "Warm Parchment", hex: "#F7F5F0", role: "subtle" },
    ],
  },
  {
    id: "venetian_velvet_gold",
    name: "Venetian Velvet & Gilded Rose",
    category: "traditional",
    categoryLabel: "Traditional & Black Tie",
    description: "Dramatic Venetian palace palette with deep crimson velvet and antique gilded gold leaf.",
    weddingTags: ["venetian", "velvet", "crimson", "gilded gold", "palace luxury"],
    swatches: [
      { name: "Venetian Crimson", hex: "#6B1D2F", role: "primary" },
      { name: "Gilded Gold Leaf", hex: "#C9A251", role: "accent" },
      { name: "Palace Cream", hex: "#FDFBF7", role: "background" },
      { name: "Midnight Espresso", hex: "#24181E", role: "neutral" },
      { name: "Antique Bronze", hex: "#8C6D3F", role: "subtle" },
    ],
  },
  {
    id: "monochrome_editorial",
    name: "Monochrome Editorial",
    category: "traditional",
    categoryLabel: "Traditional & Black Tie",
    description: "Striking black and white minimalism tailored for modern luxury typography.",
    weddingTags: ["minimalist", "monochrome", "modern", "black and white"],
    swatches: [
      { name: "Velvet Noir", hex: "#09090B", role: "primary" },
      { name: "Pure White", hex: "#FFFFFF", role: "background" },
      { name: "Charcoal Ink", hex: "#27272A", role: "accent" },
      { name: "Slate Pewter", hex: "#71717A", role: "neutral" },
      { name: "Soft Fog", hex: "#F4F4F5", role: "subtle" },
    ],
  },

  // ── 4. EDITORIAL & MODERN ──────────────────────────────────────────────────
  {
    id: "minimalist_parchment",
    name: "Minimalist Parchment",
    category: "editorial",
    categoryLabel: "Editorial & Modern",
    description: "Quiet luxury aesthetic focusing on warm tactile parchment and soft charcoal ink.",
    weddingTags: ["minimalist", "quiet luxury", "tactile", "parchment", "modern"],
    swatches: [
      { name: "Charcoal Ink", hex: "#292524", role: "primary" },
      { name: "Warm Gold", hex: "#B89748", role: "accent" },
      { name: "Soft Parchment", hex: "#F5F3EF", role: "background" },
      { name: "Taupe Neutral", hex: "#78716C", role: "neutral" },
      { name: "Alabaster", hex: "#E7E5E4", role: "subtle" },
    ],
  },
  {
    id: "high_fashion_monochrome",
    name: "High Fashion Monochrome",
    category: "editorial",
    categoryLabel: "Editorial & Modern",
    description: "Sleek magazine-style editorial palette with sharp contrast.",
    weddingTags: ["fashion", "magazine", "vogue", "sharp", "editorial"],
    swatches: [
      { name: "Deep Ink", hex: "#000000", role: "primary" },
      { name: "Champagne Gold", hex: "#D8C39D", role: "accent" },
      { name: "Vogue White", hex: "#FFFFFF", role: "background" },
      { name: "Gunmetal", hex: "#3F3F46", role: "neutral" },
      { name: "Off White", hex: "#F8F8F8", role: "subtle" },
    ],
  },

  // ── 5. AUTUMN & TERRACOTTA ─────────────────────────────────────────────────
  {
    id: "autumn_rust_dahlia",
    name: "Autumn Rust & Dahlia",
    category: "autumn",
    categoryLabel: "Autumn & Terracotta",
    description: "Rich autumnal harvest tones with warm burnt rust and honeyed dahlia gold.",
    weddingTags: ["autumn", "rust", "dahlia", "harvest", "warm terracotta"],
    swatches: [
      { name: "Burnt Terracotta Rust", hex: "#9A3412", role: "primary" },
      { name: "Honeyed Gold", hex: "#D97706", role: "accent" },
      { name: "Warm Linen", hex: "#FFFBEB", role: "background" },
      { name: "Deep Amber", hex: "#78350F", role: "neutral" },
      { name: "Oatmeal", hex: "#FEF3C7", role: "subtle" },
    ],
  },
];
